// <auto-generated />
namespace DvdShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addimagetostudio : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addimagetostudio));
        
        string IMigrationMetadata.Id
        {
            get { return "201711151354317_add-image-to-studio"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
